---
- name: Create security group with SSH to Jenkins
  ec2_group:
    name: SG Webmail Sandbox
    description: Security Group only for Webmail Sandbox
    region: "{{ region }}"
    vpc_id: "{{ vpc_id }}"
    state: present
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: "{{ ops_vpc_cidr }}"
  register: sg

- name: Start the sandbox instance
  ec2:
    region: "{{ region }}"
    image: "{{ ami }}"
    vpc_subnet_id: "{{ subnet_id }}"
    key_name: "{{ keypair_name }}"
    instance_type: "{{ instance_type }}"
    wait: true
    assign_public_ip: no
    group_id: "{{ sg.group_id }}"
    instance_tags:
        Name: Webmail base provision
  register: ec2

- name: Add new instance to host group
  add_host:
    hostname: "{{ item.private_ip }}"
    groupname: launched
  with_items: "{{ ec2.instances }}"

- name: Wait for SSH to come up
  delegate_to: "{{ item.private_ip }}"
  wait_for_connection:
    delay: 30
    timeout: 320
  with_items: "{{ ec2.instances }}"

- name: Save EC2 variable
  set_fact:
    ec2_instance_id: "{{ ec2.instance_ids[0] }}"
    cacheable: true